// scripts/makeWitness.js
const fs = require("fs");
const { execSync } = require("child_process");

const DEPTH = 3; // must match circuit

// Read the JSON input generated by buildTree.js
const raw = JSON.parse(fs.readFileSync("data/input_voter3.json", "utf8"));

const input = {
  root: raw.root,
  leaf: raw.leaf,
  secret: raw.secret,
  electionId: raw.electionId,
  pathElements: raw.pathElements.slice(0, DEPTH).map(x => x.toString()),
  pathIndices: raw.pathIndices.slice(0, DEPTH).map(Number),
};

fs.writeFileSync(
  "data/witness_input.json",
  JSON.stringify(input, null, 2)
);
console.log("📝 witness_input.json prepared");

// Measure proof-generation time
const proofStartTime = Date.now();

// Generate the witness
execSync(
  `node build/merkleInclusion_js/generate_witness.js build/merkleInclusion_js/merkleInclusion.wasm data/witness_input.json build/witness.wtns`,
  { stdio: "inherit" }
);

// Generate the proof (using your final zkey file)
execSync(
  `snarkjs groth16 prove build/merkleInclusion_final.zkey build/witness.wtns build/proof.json build/public.json`,
  { stdio: "inherit" }
);

const proofEndTime = Date.now();
const proofTime = proofEndTime - proofStartTime;
console.log(`⏱️ Proof generation time: ${proofTime}ms`);

console.log("✅ Witness and proof built (build/proof.json & build/public.json)");
